### ISSUE TITLE
Unable To Sign up 

### ISSUE THREAD

**Issue by sumukhah** [pesto-students/batch-9-Lumen#164]
On signup form submission it's doing nothing

**Comment by piyushagwl007** [comment]
@sumukhah There are some issues going on with [heroku](https://status.heroku.com/incidents/1892).      


Since Heroku does a cold start for free web application it is waiting for the latest build to be deployed.    

We are looking into if there is some issue from our side as well but as of now it seems that Heroku issue. :smiley:

**Comment by piyushagwl007** [comment]
Closing the issue as the Heroku is working fine now :smile:
